### ISSUE TITLE
LCD Screen goes blank on my Windows 10 machine about 1 per hour

### ISSUE THREAD

**Issue by PaulJohanson** [LCD-Smartie/LCDSmartie#20]
I'm running a pretty beefy Windows 10 machine. I have LCD smartie running on a Sure Electronics 4x40 display (which is pretty old). It's connected by a USB Mini port on the screen end, and a double ended USB A connected to my PC. I'm using Matrix.dll to emulate a COM port. 

![IMG_7055](https://github.com/LCD-Smartie/LCDSmartie/assets/21285080/7c8f743b-265a-421f-bc0d-4199de64771e)
![IMG_7056](https://github.com/LCD-Smartie/LCDSmartie/assets/21285080/59151dff-3f03-45b7-9861-0cb4be75e4ff)

Here's a shot of my settings:
![image](https://github.com/LCD-Smartie/LCDSmartie/assets/21285080/ed5f5036-ddd9-4e69-95ab-81ae3011b16e)
And here's a bit more detail about the drivers:
![image](https://github.com/LCD-Smartie/LCDSmartie/assets/21285080/253484d5-898d-435b-9458-f8a662b34b3b)

About once an hour, the screen will go blank. Sometimes I get a message on the app saying it can't see the COM port, but I've not managed to capture that. It doesn't write anything to the event log, nor does it seem to write any log files.

I only have two screens active, one using BigNum to show the time, and one using some of the Winamp settings (I'm still using Winamp as my main music player!)
![image](https://github.com/LCD-Smartie/LCDSmartie/assets/21285080/5bf63cbe-da25-4aee-adb0-2a709d0f51c6)
![image](https://github.com/LCD-Smartie/LCDSmartie/assets/21285080/c9feed14-36ea-4692-8656-73ed945688b0)

My guess is the crusty USB to COM driver I'm using is to blame. I've not been able to find a more recent one, if anyone has suggestions about alternatives please tell me! Or indeed if it's time I updated to a more recent display.

I'm probably skilled enough to actually clone the repo and build it for myself, I was a developer for many years before moving into management. But I also have limited spare time, so any suggestions would be appreciated.

**Comment by stokie-ant** [comment]
Could you give this test version a try [LCDSmartie_exe_5.6.0.1 (1).zip](https://drive.google.com/file/d/1tJR39M4D0ywB_hvO6dulsitZq_jPtpLc/view?usp=drive_link)
I recently fixed an issue where under some condition the power event handler would be triggered. I don't know if this is a similar issue

**Comment by Labrat-alter** [comment]
I have same problem with lcd2usb, after about 2-3 hours screen goes blank

**Comment by stokie-ant** [comment]
Did you try the test version above? Or, if you don't have a shutdown message set could you set one to see if it being shown when the bug is triggered

**Comment by Labrat-alter** [comment]
I've just set shutdown message, now We have to wait. 
I'll try updated version and give You a feedback if problem occurred or not.

**Comment by stokie-ant** [comment]
If it's unrelated please open another issue. That way I can keep track of what's being fixed

**Comment by PaulJohanson** [comment]
> Could you give this test version a try [LCDSmartie_exe_5.6.0.1 (1).zip](https://drive.google.com/file/d/1tJR39M4D0ywB_hvO6dulsitZq_jPtpLc/view?usp=drive_link) I recently fixed an issue where under some condition the power event handler would be triggered. I don't know if this is a similar issue

Trying this out now...

**Comment by PaulJohanson** [comment]
So far so good, the app has been running on my machine for about 6 hours today without the LCD screen going blank.

**Comment by PaulJohanson** [comment]
I'm going to call this one fixed, in the 5.6.0.1 build. Hasn't reoccurred in two solid days of running the screen
