### ISSUE TITLE
Parcially cleaned LCD screen when turning off PC

### ISSUE THREAD

**Issue by Labrat-alter** [LCD-Smartie/LCDSmartie#21]
I have a problem when I turn off my PC and LCDSmartie still runs and the LCD is still active, my computer turns off but the LCD partially cleans (two out of four lines and about six out of twenty characters) and stays in that state.
Probably application is forced to close during shutdown procedure.

**Comment by stokie-ant** [comment]
What display driver are you using? Does this only happen during shutdown or does it happen when manually closed also?

**Comment by Labrat-alter** [comment]
I'm using LCD2USB, Yes it's only happening during shutdown if I manually close LCD Smartie screen goes completely clean.

**Comment by stokie-ant** [comment]
OK, I have an LCD2USB device. I'll take a look and get back to you

**Comment by stokie-ant** [comment]
I've taken a look but unfortunately I cant reproduce this. It seems to work fine with a 2x16 display but I don't have a 4 line to test with.
Does the shutdown message get partially written?

**Comment by Labrat-alter** [comment]
The shutdown message is written completely each time and It seems like the problem is solved.
